# Generated by Django 5.2.10 on 2026-07-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepayment',
            name='first_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='servicepayment',
            name='last_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='category',
            field=models.CharField(choices=[('bogcha_davlat', "🏛️ Davlat bog'chasi"), ('bogcha_shaxsiy', "🧸 Shaxsiy bog'cha"), ('kurs', "📚 O'quv kurslari"), ('maktab', '🏫 Maktab / litsey')], db_index=True, max_length=20, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='category',
            field=models.CharField(choices=[('bogcha_davlat', "🏛️ Davlat bog'chasi"), ('bogcha_shaxsiy', "🧸 Shaxsiy bog'cha"), ('kurs', "📚 O'quv kurslari"), ('maktab', '🏫 Maktab / litsey')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='payer_name',
            field=models.CharField(blank=True, help_text="Bola / o'quvchi ism-familiyasi (ism va familiyadan avtomatik tuziladi)", max_length=150, verbose_name="To'lovchi (ism-familiya)"),
        ),
    ]
