# Generated by Django 5.2.10 on 2026-07-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_servicepayment_first_name_servicepayment_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='category',
            field=models.CharField(choices=[('bogcha_davlat', "🏛️ Davlat bog'chasi"), ('bogcha_shaxsiy', "🧸 Shaxsiy bog'cha"), ('kurs', "📚 O'quv kurslari"), ('maktab', '🏫 Maktab / litsey'), ('bogcha', "🧒 Bog'cha"), ('boshqa', '📦 Boshqa'), ('internet', '🌐 Internet'), ('kommunal', '💡 Kommunal')], db_index=True, max_length=20, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='category',
            field=models.CharField(choices=[('bogcha_davlat', "🏛️ Davlat bog'chasi"), ('bogcha_shaxsiy', "🧸 Shaxsiy bog'cha"), ('kurs', "📚 O'quv kurslari"), ('maktab', '🏫 Maktab / litsey'), ('bogcha', "🧒 Bog'cha"), ('boshqa', '📦 Boshqa'), ('internet', '🌐 Internet'), ('kommunal', '💡 Kommunal')], db_index=True, max_length=20),
        ),
    ]
