# Generated by Django 5.2.10 on 2026-07-02 08:03

import django.db.models.deletion
import main.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_driverlocation_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Mijoz tomonidan tasdiqlangan vaqt'),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('delivery', 'Yetkazib berish'), ('pickup', "O'zi olib ketish")], default='delivery', max_length=10, verbose_name='Yetkazish turi'),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_for_pickup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Olib ketishga tayyor bo'lgan vaqt"),
        ),
        migrations.AddField(
            model_name='product',
            name='restock_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qayta kelish vaqti'),
        ),
        migrations.AddField(
            model_name='store',
            name='owner_bio',
            field=models.TextField(blank=True, verbose_name="Do'kon egasi haqida"),
        ),
        migrations.AddField(
            model_name='store',
            name='owner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/owners/', validators=[main.utils.validate_file_type], verbose_name='Egasi rasmi'),
        ),
        migrations.AddField(
            model_name='store',
            name='working_hours',
            field=models.CharField(blank=True, help_text='Masalan: 9:00–22:00, har kuni', max_length=200, verbose_name='Ish vaqti'),
        ),
        migrations.CreateModel(
            name='StoreChatThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_chat_threads', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='delivery.store')),
            ],
            options={
                'verbose_name': "Do'kon chat mavzusi",
                'verbose_name_plural': "Do'kon chat mavzulari",
                'db_table': 'delivery_store_chat_threads',
                'unique_together': {('store', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='StoreChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='delivery.storechatthread')),
            ],
            options={
                'verbose_name': "Do'kon chat xabari",
                'verbose_name_plural': "Do'kon chat xabarlari",
                'db_table': 'delivery_store_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='delivery/stores/gallery/%Y/%m/', validators=[main.utils.validate_file_type])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='delivery.store')),
            ],
            options={
                'verbose_name': "Do'kon galereya rasmi",
                'verbose_name_plural': "Do'kon galereya rasmlari",
                'db_table': 'delivery_store_images',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Yoqilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='delivery.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Do'kon obunasi",
                'verbose_name_plural': "Do'kon obunalari",
                'db_table': 'delivery_store_subscriptions',
                'unique_together': {('store', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StoreUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('new_product', 'Yangi mahsulot'), ('price_changed', 'Narx yangilandi'), ('restocked', 'Qayta keldi'), ('out_of_stock', 'Tugadi'), ('announcement', "E'lon")], max_length=20, verbose_name='Turi')),
                ('text', models.TextField(blank=True, verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='delivery/updates/%Y/%m/', validators=[main.utils.validate_file_type])),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='delivery.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='delivery.store')),
            ],
            options={
                'verbose_name': "Do'kon yangiligi",
                'verbose_name_plural': "Do'kon yangiliklari",
                'db_table': 'delivery_store_updates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', '-created_at'], name='store_update_store_created_idx')],
            },
        ),
    ]
