# Generated by Django 5.2.10 on 2026-07-02 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_order_customer_confirmed_at_order_fulfillment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Olib ketish vaqti (mijoz tanlagan)'),
        ),
        migrations.AddField(
            model_name='store',
            name='pickup_enabled',
            field=models.BooleanField(default=False, help_text="Yoqilsa — mijozlar oldindan to'lab, do'kondan o'zi olib ketadi.", verbose_name='Olib ketish (pickup) yoqilgan'),
        ),
        migrations.AddField(
            model_name='storechatthread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='storechatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='store_chat_thread_created_idx'),
        ),
    ]
