# Generated by Django 5.2.10 on 2026-07-03 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_order_pickup_at_store_pickup_enabled_and_more'),
        ('main', '0025_neighborhood_head_name_neighborhood_head_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='main.neighborhood', verbose_name='Mahalla'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('delivery', "Yetkazib beruvchi do'kon"), ('mahalla', "Mahalla do'koni")], db_index=True, default='delivery', max_length=10, verbose_name="Do'kon turi"),
        ),
        migrations.CreateModel(
            name='StoreRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Do'kon nomi")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], db_index=True, default='pending', max_length=10)),
                ('admin_note', models.CharField(blank=True, max_length=300, verbose_name='Admin izohi (rad sababi/javob)')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='delivery.store')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_requests', to='main.neighborhood', verbose_name='Mahalla')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_store_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Mahalla do'kon arizasi",
                'verbose_name_plural': "Mahalla do'kon arizalari",
                'db_table': 'delivery_store_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['neighborhood', 'status'], name='storereq_nbhd_status_idx')],
            },
        ),
    ]
