# Generated by Django 5.2.10 on 2026-07-03 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_store_neighborhood_store_store_type_storerequest'),
        ('main', '0025_neighborhood_head_name_neighborhood_head_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-is_active', 'created_at'], 'verbose_name': 'Savat', 'verbose_name_plural': 'Savatlar'},
        ),
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol savat'),
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='Asosiy savat', max_length=80, verbose_name='Savat nomi'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CheckoutGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checkout guruhi',
                'verbose_name_plural': 'Checkout guruhlari',
                'db_table': 'delivery_checkout_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.checkoutgroup'),
        ),
        migrations.CreateModel(
            name='CartAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_saves', to='main.ad')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_items', to='delivery.cart')),
            ],
            options={
                'verbose_name': "Savatdagi e'lon",
                'verbose_name_plural': "Savatdagi e'lonlar",
                'db_table': 'delivery_cart_ads',
                'ordering': ['-added_at'],
                'unique_together': {('cart', 'ad')},
            },
        ),
    ]
