# Generated by Django 5.2.10 on 2026-07-12 12:05

import django.db.models.deletion
import main.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_driverreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nomi')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='Brend')),
                ('unit', models.CharField(choices=[('piece', 'dona'), ('bottle', 'shisha'), ('liter', 'litr'), ('kg', 'kg'), ('gram', 'gramm'), ('pack', 'paket'), ('tray', 'fletka'), ('box', 'quti'), ('ml', 'ml')], default='piece', max_length=10, verbose_name="O'lchov birligi")),
                ('image', models.ImageField(blank=True, null=True, upload_to='delivery/catalog/%Y/%m/', validators=[main.utils.validate_file_type], verbose_name='Rasm')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_products', to='delivery.deliverycategory', verbose_name='Kategoriya')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalog_products', to=settings.AUTH_USER_MODEL)),
                ('promoted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='delivery.product', verbose_name="Manba (do'kon mahsuloti)")),
            ],
            options={
                'verbose_name': 'Katalog mahsuloti',
                'verbose_name_plural': 'Katalog mahsulotlari',
                'db_table': 'delivery_catalog_products',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='catalog_product',
            field=models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa — do'konning o'z (custom) mahsuloti.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_products', to='delivery.catalogproduct', verbose_name='Katalog mahsuloti'),
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['name'], name='catalog_name_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['category', 'is_active'], name='catalog_cat_active_idx'),
        ),
    ]
