# Generated by Django 5.2.10 on 2026-07-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='suggested_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Tavsiya narx (so'm)"),
        ),
    ]
