# Generated by Django 5.2.10 on 2026-08-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0020_catalogproduct_suggested_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('preparing', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('assigned', 'Haydovchi biriktirildi'), ('picked_up', "Kuryer do'kondan oldi"), ('on_the_way', "Yo'lda"), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilingan')], db_index=True, default='pending', max_length=20),
        ),
    ]
