# Generated by Django 5.2.10 on 2026-08-16 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def approve_existing_drivers(apps, schema_editor):
    """Mavjud kuryerlarni TASDIQLANGAN deb belgilaydi.

    Yangi maydonning default'i 'pending' — u faqat bundan keyingi arizalar
    uchun. Migratsiya buni tuzatmasa, allaqachon ishlab yurgan kuryerlarning
    hammasi bir zumda bloklanib qolardi (qo'lidagi buyurtmalar bilan birga).
    """
    Driver = apps.get_model('delivery', 'DeliveryDriver')
    Driver.objects.update(status='approved')


def unapprove_all(apps, schema_editor):
    """Ortga qaytarish — maydon o'chiriladi, ma'lumot tiklanmaydi."""


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydriver',
            name='reject_reason',
            field=models.CharField(blank=True, help_text="Rad etilsa arizachiga shu matn ko'rsatiladi.", max_length=300, verbose_name='Rad etish sababi'),
        ),
        migrations.AddField(
            model_name='deliverydriver',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqt"),
        ),
        migrations.AddField(
            model_name='deliverydriver',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_drivers', to=settings.AUTH_USER_MODEL, verbose_name="Kim ko'rib chiqdi"),
        ),
        migrations.AddField(
            model_name='deliverydriver',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Tasdiq kutilmoqda'), ('approved', '✅ Tasdiqlangan'), ('rejected', '❌ Rad etilgan')], db_index=True, default='pending', max_length=10, verbose_name='Tasdiq holati'),
        ),
        migrations.RunPython(approve_existing_drivers, unapprove_all),
    ]
