# Generated by Django 5.2.10 on 2026-08-17 06:21

from django.db import migrations, models


def foot_to_bike(apps, schema_editor):
    """Piyoda kuryerlarni velosipedga o'tkazadi.

    'foot' variant olib tashlandi. Ko'chirilmasa, mavjud yozuvlar
    `get_vehicle_type_display()` da bo'sh chiqadi va tanlov ro'yxatida
    hech nima belgilanmagan holatga tushadi.
    """
    apps.get_model('delivery', 'DeliveryDriver').objects.filter(
        vehicle_type='foot').update(vehicle_type='bike')


def bike_to_foot(apps, schema_editor):
    """Ortga qaytarish — ma'lumot yo'qolmasin uchun teskari amal yo'q.

    Qaysi velosipedchi ilgari piyoda bo'lganini bilib bo'lmaydi, shuning
    uchun ortga qaytarishda hech narsa o'zgartirilmaydi.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0022_deliverydriver_reject_reason_and_more'),
    ]

    operations = [
        migrations.RunPython(foot_to_bike, bike_to_foot),
        migrations.AlterField(
            model_name='deliverydriver',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', '🚲 Velosiped'), ('moto', '🏍️ Mototsikl'), ('car', '🚗 Avtomobil')], default='moto', max_length=10, verbose_name='Transport turi'),
        ),
    ]
