# Generated by Django 5.2.11 on 2026-06-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_views'),
        ('places', '0002_placereview_placefavorite'),
    ]

    operations = [
    ]
