# Generated by Django 5.2.11 on 2026-06-20 18:20

import django.core.validators
import main.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_merge_0002_place_views_0002_placereview_placefavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/%Y/%m/', validators=[main.utils.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Kenglik (latitude)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Uzunlik (longitude)'),
        ),
        migrations.AlterField(
            model_name='placereview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_active', 'category'], name='place_active_cat_idx'),
        ),
    ]
