# Generated by Django 5.2.10 on 2026-07-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('furniture', "Mebel do'konlari"), ('electronics', "Elektronika do'konlari"), ('tourist', 'Diqqatga sazovor joylar'), ('government', 'Davlat binolari'), ('organization', 'Tashkilot ofislari'), ('post', "Pochta bo'limlari"), ('bank', 'Banklar'), ('pharmacy', 'Dorixonalar'), ('hospital', 'Shifoxonalar'), ('hotel', 'Mehmonxonalar'), ('wedding', "To'yxonalar"), ('restaurant', 'Restoranlar'), ('delivery_store', "Do'konlar"), ('school', 'Maktablar'), ('kindergarten', "Bog'chalar"), ('barber', 'Sartaroshxonalar')], db_index=True, max_length=30, verbose_name='Toifa'),
        ),
    ]
