# Generated by Django 5.2.10 on 2026-07-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Tavsif (inglizcha)'),
        ),
        migrations.AddField(
            model_name='place',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsif (ruscha)'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nomi (inglizcha)'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nomi (ruscha)'),
        ),
    ]
