# Generated by Django 5.2.10 on 2026-08-16 04:44

import django.db.models.deletion
import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_place_description_en_place_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('salad', 'Salatlar'), ('soup', "Sho'rvalar"), ('main', 'Asosiy taomlar'), ('grill', 'Kabob / grill'), ('bakery', 'Non va patir'), ('dessert', 'Shirinliklar'), ('drink', 'Ichimliklar'), ('other', 'Boshqa')], db_index=True, default='main', max_length=20, verbose_name="Bo'lim")),
                ('name', models.CharField(max_length=150, verbose_name='Taom nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tarkibi / tavsif')),
                ('price', models.BigIntegerField(verbose_name="Narx (so'm)")),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/menu/%Y/%m/', validators=[main.utils.validate_file_type], verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name="Menyuda ko'rsatilsin")),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='places.place')),
            ],
            options={
                'verbose_name': 'Menyu taomi',
                'verbose_name_plural': 'Menyu taomlari',
                'db_table': 'place_menu_items',
                'ordering': ['section', 'order', 'name'],
                'indexes': [models.Index(fields=['place', 'is_active'], name='menu_place_active_idx')],
            },
        ),
    ]
