# Generated by Django 5.2.10 on 2026-07-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Telefon')),
                ('chat_id', models.BigIntegerField(verbose_name='Telegram chat ID')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='Username')),
                ('linked_at', models.DateTimeField(auto_now=True, verbose_name='Ulangan vaqti')),
            ],
            options={
                'verbose_name': "Telegram bog'lanish",
                'verbose_name_plural': "Telegram bog'lanishlar",
                'db_table': 'telegram_links',
                'ordering': ['-linked_at'],
            },
        ),
    ]
