# Generated by Django 5.2.10 on 2026-08-15 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_venuebooking_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Xizmat haqida'),
        ),
        migrations.AddField(
            model_name='venueservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='venues/services/%Y/%m/', verbose_name='Rasm'),
        ),
        migrations.CreateModel(
            name='VenueWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Ish nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='venues/works/%Y/%m/', verbose_name='Rasm')),
                ('price', models.BigIntegerField(blank=True, null=True, verbose_name="Narx (so'm)")),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rsatilsin")),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='booking.venueservice', verbose_name='Xizmat')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='booking.venuestaff', verbose_name='Usta/ishchi')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='booking.venue')),
            ],
            options={
                'verbose_name': 'Bajarilgan ish',
                'verbose_name_plural': 'Bajarilgan ishlar',
                'db_table': 'venue_works',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
