# Generated by Django 5.2.10 on 2026-08-16 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_venueservice_description_venueservice_image_and_more'),
        ('places', '0008_placemenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='places.place', verbose_name='Xaritadagi joy'),
        ),
    ]
