# Generated by Django 5.2.10 on 2026-08-16 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_venue_place'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venuestaff',
            name='phone',
            field=models.CharField(blank=True, help_text='Shu raqamli foydalanuvchi topilsa, ustaga panel ochiladi.', max_length=30, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='venuestaff',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_roles', to=settings.AUTH_USER_MODEL, verbose_name='Hisob (panelga kirish uchun)'),
        ),
    ]
