# Generated by Django 5.2.10 on 2026-08-16 19:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_venuestaff_phone_venuestaff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='Sana')),
                ('start_time', models.TimeField(blank=True, help_text="Bo'sh qoldirilsa — butun kun yopiq.", null=True, verbose_name='Boshlanish')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Tugash')),
                ('reason', models.CharField(blank=True, max_length=120, verbose_name='Sabab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='booking.venuestaff')),
            ],
            options={
                'verbose_name': 'Usta yopgan vaqt',
                'verbose_name_plural': 'Usta yopgan vaqtlar',
                'db_table': 'venue_staff_time_off',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['staff', 'date'], name='stf_off_staff_date_idx')],
            },
        ),
    ]
