# Generated by Django 5.2.10 on 2026-08-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_stafftimeoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuebooking',
            name='actual_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Yakunlanganda hisoblanadi — taxminiy vaqtni aniqlashtiradi.', null=True, verbose_name='Haqiqiy davomiylik (daqiqa)'),
        ),
        migrations.AddField(
            model_name='venuebooking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt'),
        ),
    ]
