# Generated by Django 5.2.10 on 2026-08-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_venuebooking_actual_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('wedding', "💍 To'yxona"), ('restaurant', '🍽️ Restoran'), ('barber', '💈 Sartaroshxona'), ('gym', '🏋️ Sport zal'), ('cafe', '☕ Kafe'), ('beauty', "💅 Go'zallik saloni"), ('clinic', '🏥 Klinika'), ('other', '📍 Boshqa')], db_index=True, default='other', max_length=20, verbose_name='Turi'),
        ),
    ]
