# Generated by Django 5.2.11 on 2026-06-05 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('code', models.CharField(max_length=6)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('business', 'Biznes'), ('driver', 'Haydovchi'), ('admin', 'Admin')], default='user', max_length=20)),
                ('avatar_url', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='main_user_set', related_query_name='main_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='main_user_set', related_query_name='main_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('uy_joy', 'Uy-joy'), ('ish', 'Ish'), ('avtomobil', 'Avtomobil'), ('qishloq', "Qishloq xo'jaligi"), ('kurs', "Kurs/Ta'lim"), ('xizmat', 'Xizmat'), ('hayvonlar', 'Hayvonlar'), ('boshqa', 'Boshqa')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('price_type', models.CharField(choices=[('fixed', 'Belgilangan'), ('negotiable', 'Muzokarali'), ('free', 'Bepul')], default='fixed', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('sold', 'Sotilgan'), ('expired', "Muddati o'tgan"), ('deleted', "O'chirilgan")], db_index=True, default='active', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_boosted', models.BooleanField(default=False)),
                ('boosted_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ads',
                'ordering': ['-is_boosted', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='ads/%Y/%m/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.ad')),
            ],
            options={
                'db_table': 'ad_images',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['category', 'status'], name='ads_categor_3c1f64_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['user', 'status'], name='ads_user_id_da218a_idx'),
        ),
    ]
