# Generated by Django 5.2.11 on 2026-06-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_course_boost'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ad',
            name='ads_categor_3c1f64_idx',
        ),
        migrations.RemoveIndex(
            model_name='ad',
            name='ads_user_id_da218a_idx',
        ),
    ]
