# Generated by Django 5.2.11 on 2026-06-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_ad_ads_categor_3c1f64_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='venue_booking_enabled',
            field=models.BooleanField(default=True, verbose_name='Venue bron tizimi'),
        ),
    ]
