# Generated by Django 5.2.11 on 2026-06-12 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_ad_venue_booking_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_admin_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ChatAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='main.neighborhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_admin_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat admini',
                'verbose_name_plural': 'Chat adminlari',
                'db_table': 'chat_admins',
                'unique_together': {('neighborhood', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Bloklangan')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Chat a'zosi",
                'verbose_name_plural': "Chat a'zolari",
                'db_table': 'chat_members',
                'unique_together': {('room', 'user')},
            },
        ),
    ]
