# Generated by Django 5.2.11 on 2026-06-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0015_remove_business_course_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='main_user_set', related_query_name='main_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='main_user_permissions', related_query_name='main_user_perm', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
