# Generated by Django 5.2.11 on 2026-06-20 18:20

import django.core.validators
import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_marketplace_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(upload_to='ads/%Y/%m/', validators=[main.utils.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', "OTP kod 6 ta raqamdan iborat bo'lishi kerak.")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', validators=[main.utils.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', "Telefon raqamini to'g'ri kiriting (masalan: +998901234567).")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status', '-is_boosted', '-created_at'], name='ad_status_boost_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['user', 'status'], name='ad_user_status_idx'),
        ),
    ]
