# Generated by Django 5.2.11 on 2026-06-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_coordinate_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobad',
            name='company_description',
            field=models.TextField(blank=True, verbose_name='Kompaniya haqida'),
        ),
        migrations.AddField(
            model_name='jobad',
            name='manager_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Menejer ismi'),
        ),
        migrations.AddField(
            model_name='jobad',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Menejer telefoni'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Belgilangan'), ('free', 'Bepul')], default='fixed', max_length=20),
        ),
    ]
