# Generated by Django 5.2.10 on 2026-06-30 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_jobad_company_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='main.neighborhood', verbose_name='Mahalla'),
        ),
    ]
