# Generated by Django 5.2.10 on 2026-06-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_user_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='boundary',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Chegara (poligon)'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='center_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Markaz (kenglik)'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='center_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Markaz (uzunlik)'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='color',
            field=models.CharField(blank=True, default='#3551d1', max_length=9, verbose_name='Rang'),
        ),
    ]
