# Generated by Django 5.2.10 on 2026-07-03 08:04

import django.db.models.deletion
import main.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_neighborhood_boundary_neighborhood_center_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='head_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Mahalla raisi'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='head_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Rais telefoni'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Aholi soni'),
        ),
        migrations.CreateModel(
            name='CitizenRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('road', "Yo'l"), ('water', 'Suv'), ('electricity', 'Svet / elektr'), ('cleaning', 'Tozalik'), ('gas', 'Gaz'), ('lighting', "Ko'cha yoritilishi"), ('landscaping', 'Obodonlashtirish'), ('other', 'Boshqa')], db_index=True, default='other', max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('text', models.TextField(verbose_name='Murojaat matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mahalla/requests/%Y/%m/', validators=[main.utils.validate_file_type])),
                ('status', models.CharField(choices=[('submitted', 'Yuborildi'), ('reviewing', "Ko'rib chiqilmoqda"), ('resolved', 'Hal qilindi'), ('rejected', 'Rad etildi')], db_index=True, default='submitted', max_length=15)),
                ('response', models.TextField(blank=True, verbose_name='Rais/admin javobi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_requests', to='main.neighborhood', verbose_name='Mahalla')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fuqaro murojaati',
                'verbose_name_plural': 'Fuqaro murojaatlari',
                'db_table': 'citizen_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['neighborhood', 'status', '-created_at'], name='citizen_req_nb_status_idx'), models.Index(fields=['user', '-created_at'], name='citizen_req_user_idx')],
            },
        ),
        migrations.CreateModel(
            name='NeighborhoodAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('text', models.TextField(verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mahalla/announcements/%Y/%m/', validators=[main.utils.validate_file_type])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighborhood_announcements', to=settings.AUTH_USER_MODEL)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='main.neighborhood', verbose_name='Mahalla')),
            ],
            options={
                'verbose_name': "Mahalla e'loni",
                'verbose_name_plural': "Mahalla e'lonlari",
                'db_table': 'neighborhood_announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['neighborhood', '-created_at'], name='nb_ann_created_idx')],
            },
        ),
    ]
