# Generated by Django 5.2.10 on 2026-07-11 05:47

import django.db.models.deletion
import main.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_neighborhood_head_name_neighborhood_head_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tuman nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('head_name', models.CharField(blank=True, max_length=120, verbose_name='Hokim (F.I.O.)')),
                ('head_phone', models.CharField(blank=True, max_length=30, verbose_name='Hokim telefoni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'db_table': 'districts',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighborhoods', to='main.district', verbose_name='Tuman'),
        ),
        migrations.CreateModel(
            name='DistrictAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='main.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_admin_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tuman hokimi',
                'verbose_name_plural': 'Tuman hokimlari',
                'db_table': 'district_admins',
                'unique_together': {('district', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DistrictAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('text', models.TextField(verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tuman/announcements/%Y/%m/', validators=[main.utils.validate_file_type])),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Yuborilganlar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_announcements', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='main.district', verbose_name='Tuman')),
            ],
            options={
                'verbose_name': "Tuman e'loni",
                'verbose_name_plural': "Tuman e'lonlari",
                'db_table': 'district_announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['district', '-created_at'], name='dist_ann_created_idx')],
            },
        ),
    ]
