# Generated by Django 5.2.10 on 2026-07-11 09:09

import django.db.models.deletion
import main.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_district_neighborhood_district_districtadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jins'),
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('text', models.TextField(verbose_name='Matn')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='Havola (ixtiyoriy)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/campaigns/%Y/%m/', validators=[main.utils.validate_file_type], verbose_name='Rasm')),
                ('gender', models.CharField(blank=True, choices=[('', "Farqi yo'q"), ('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jins')),
                ('age_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yosh (dan)')),
                ('age_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yosh (gacha)')),
                ('role', models.CharField(blank=True, choices=[('', "Farqi yo'q"), ('user', 'Foydalanuvchi'), ('business', 'Biznes'), ('driver', 'Haydovchi')], max_length=20, verbose_name='Rol')),
                ('target_count', models.PositiveIntegerField(default=50, verbose_name='Nechta kishiga (random)')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('sent', 'Yuborilgan')], db_index=True, default='draft', max_length=10)),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Yuborildi (fakt)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaigns', to='main.district', verbose_name='Tuman (ixtiyoriy)')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaigns', to='main.neighborhood', verbose_name='Mahalla (ixtiyoriy)')),
            ],
            options={
                'verbose_name': 'Reklama kampaniyasi',
                'verbose_name_plural': 'Reklama kampaniyalari',
                'db_table': 'ad_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdCampaignDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='main.adcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_campaign_deliveries',
                'indexes': [models.Index(fields=['user', '-sent_at'], name='adcamp_user_sent_idx')],
            },
        ),
    ]
