# Generated by Django 5.2.10 on 2026-07-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_user_birth_date_user_gender_adcampaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='send_to_all',
            field=models.BooleanField(default=False, help_text="Yoqilsa — filtrlarga mos BARCHA faol foydalanuvchiga bir vaqtda yuboriladi (random N va kuniga-1 cheklovisiz). Filtrlar bo'sh bo'lsa — butun bazadagi hamma foydalanuvchiga.", verbose_name='Hammaga yuborish'),
        ),
    ]
