# Generated by Django 5.2.10 on 2026-07-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_neighborhood_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['name'], 'verbose_name': 'Mahalla', 'verbose_name_plural': 'Mahallalar'},
        ),
    ]
