# Generated by Django 5.2.10 on 2026-08-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_neighborhood_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='adinquiry',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
