# Generated by Django 5.2.10 on 2026-08-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_adinquiry_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='contact_facebook',
        ),
    ]
