# Generated by Django 5.2.10 on 2026-07-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('order', 'Buyurtma'), ('booking', 'Bron'), ('taxi', 'Taksi'), ('chat', 'Chat'), ('business', 'Biznes'), ('ads', 'Reklama'), ('system', 'Tizim')], default='system', max_length=20),
        ),
    ]
